### ISSUE TITLE
Host(Organiser) details of Invitee registration 

### ISSUE THREAD

**Issue by bugdimes** [koshilife/calendly-api-ruby-client#51]
Hi, Since there are multiple event types, suppose there is an Round robin event, and Upon registration (#event_invitee) which returns Calendly::Invitee

Is there a way, I could know the assigned host(member) out of the registration
If the event is One to One, then I maybe get the host details from the Event

But in case of Round Robin Event types, I would like to know the Host for a meetin

I was not able to see any instance method which brings such details

Thanks in advanced

**Comment by koshilife** [comment]
Hi @bugdimes,

There are no APIs about this as long as I know.
If you contact the Calendly Developer team, you might find out a better solution. The below link would let you know their email address.

https://developer.calendly.com/get-help
